services:
  placemaker-bot:
    build: .
    container_name: placemaker-bot
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s

  ngrok:
    image: ngrok/ngrok:latest
    container_name: placemaker-ngrok
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http placemaker-bot:8000
    depends_on:
      - placemaker-bot
    ports:
      - "4040:4040" 